name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
         channel: stable
         flutter-version: 3.24.2
      - name: Run tests
        run: flutter test
      - name: Generate docs
        run: dart doc
      - name: Upload doc artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./doc/api"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GitHub pages
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
